name: .NET

on:
  push:
    branches: [ master ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore
      run: dotnet restore
      

    - name: Build
      run: dotnet build 
    
    - name: Publish
      run: |  
       
          dotnet pack -c Release -o out  

    
        
    - name: Add private GitHub registry to NuGet
      run: nuget sources add -name "GPR" -Source https://nuget.pkg.github.com/sanjanasenthilkumar/index.json -Username sanjanasenthilkumar -Password ${{ secrets.GITHUB_TOKEN }}
        
    - name: Push generated package to GitHub registry
       
      run: dotnet nuget push ./dotnetcore-hello-world/out/*.nupkg --source "GPR" --SkipDuplicate
    - name: Test
      run: dotnet test --no-build --verbosity normal
